name: Build macOS kits
on:
  workflow_dispatch:
  workflow_call:

env:
  TCL_TK_VERSION: 8.6.15
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
  KC_TLS_SSLDIR: /opt/local
  KC_TLS_LINKSSLSTATIC: 1
  STATICTK: 0
  STATICTKSVG: 0
  STATICTLS: 1
  STATICTDOM: 1
  STATICTCLX: 1
  STATICPARSE_ARGS: 1
  STATICTRF: 1
  STATICZLIBTCL: 1
  STATICTCLLIB: 1
  STATICMK4: 1

jobs:
  build-macos-kits:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: melusina-org/setup-macports@v1
        with:
          parameters: '.github/parameters/setup-macports.yaml'
      - name: Setup environment
        run: |
          arch=$(uname -m)
          os=$(echo "$(uname)$(uname -r)" | tr '[:upper:]' '[:lower:]')
          cat <<EOF > $GITHUB_ENV
          suffix=${arch}-apple-${os}
          EOF

      - name: Minimal kit (No GUI)
        env:
          KITCREATOR_PKGS: mk4tcl
        run: |
          ./build/pre.sh
          ./kitcreator build ${{env.TCL_TK_VERSION}}
          mv tclkit-${{env.TCL_TK_VERSION}} tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          echo "$KITCREATOR_PKGS" > tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal.kc_packages
          cat <<EOF > $GITHUB_ENV
          TCLKIT=$(pwd)/tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          TCLSH_NATIVE=$(pwd)/tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          EOF

      - name: Minimal kit (With GUI)
        env:
          KITCREATOR_PKGS: 'tk mk4tcl'
        run: |
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-aqua
          mv tclkit-${{env.TCL_TK_VERSION}} tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          echo "$KITCREATOR_PKGS" > tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal.kc_packages
          rm -f  tk/.success
          rm -rf tk/{out,inst,build}

      - name: Standard kit (No GUI)
        env:
          KITCREATOR_PKGS: 'tcllib tls tdom tclx parse_args Trf zlibtcl mk4tcl'
        run: |
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-tcl-private-headers
          mv tclkit-${{env.TCL_TK_VERSION}} tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}
          echo "$KITCREATOR_PKGS" > tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}.kc_packages

      - name: Full kit (with GUI)
        env:
          KITCREATOR_PKGS: 'tk tksvg tcllib tls tdom tclx parse_args Trf zlibtcl mk4tcl'
        run: |
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-aqua --enable-tcl-private-headers
          mv tclkit-${{env.TCL_TK_VERSION}} tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}
          echo "$KITCREATOR_PKGS" > tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}.kc_packages

      - name: Kit SDK
        env:
          KITCREATOR_PKGS: 'tk mk4tcl kitdll'
          STATICTK: 1
        run: |
          clean_all_but_tcl_and_mk4() {
            for pkg in $(ls */build.sh | cut -d/ -f1 | egrep -v '^(tcl|mk4tcl)$'); do
              rm -f  "${pkg}/.success"
              rm -rf "${pkg}/out" "${pkg}/inst" "${pkg}/build"
            done
          }
          clean_all_but_tcl_and_mk4
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-aqua --enable-tcl-private-headers
          mv libtclkit-sdk-${{env.TCL_TK_VERSION}}.tar.gz libtclkit-sdk-${{env.TCL_TK_VERSION}}-${{env.suffix}}.tar.gz
          echo "$KITCREATOR_PKGS" > libtclkit-sdk-${{env.TCL_TK_VERSION}}-${{env.suffix}}.tar.gz.kc_packages

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: kitcreator-macos-logs
          path: |
            **/build.log
            **/config.log

      - name: Upload kitcreator output
        uses: actions/upload-artifact@v4
        with:
          name: kitcreator-macos-kits
          path: |
            tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
            tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
            tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}
            tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}
            libtclkit-sdk-${{env.TCL_TK_VERSION}}-${{env.suffix}}.tar.gz
        if: ${{ !cancelled() }}

      - name: Upload kitcreator package list
        uses: actions/upload-artifact@v4
        with:
          name: kitcreator-macos-kc_packages
          path: |
            *.kc_packages
        if: ${{ !cancelled() }}
