name: Build macOS kits
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]

env:
  TCL_TK_VERSION: 8.6.16
  CC: /usr/bin/clang
  CXX: /usr/bin/clang++
  KC_TLS_LINKSSLSTATIC: 1
  STATICTK: 0
  STATICTKSVG: 0
  STATICTLS: 1
  STATICTDOM: 1
  STATICPARSE_ARGS: 1
  STATICTCLLIB: 1
  STATICMK4: 1
  CFLAGS:   '-DNDEBUG -O2 -fomit-frame-pointer -fstack-protector-strong -ffunction-sections -fdata-sections'
  CPPFLAGS: '-DNDEBUG -O2 -fomit-frame-pointer -fstack-protector-strong -ffunction-sections -fdata-sections'
  CXXFLAGS: '-DNDEBUG -O2 -fomit-frame-pointer -fstack-protector-strong -ffunction-sections -fdata-sections'
  KC_KITSH_LDFLAGS: '-Wl,-dead_strip'
  CODESIGN_SIGNATURE: ${{ secrets.CODESIGN_SIGNATURE }}
  CODESIGN_PREFIX: com.bandoti.

jobs:
  build-macos-kits:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Packages
        run: |
          brew update
          brew install autoconf automake libtool groff cmake openssl@3 curl create-dmg
          cat <<EOF >> $GITHUB_ENV
          KC_TLS_SSLDIR=$(brew --prefix openssl@3)
          EOF

      - name: Import Code Signing Certificate
        env:
          CERTIFICATE_BASE64:   ${{ secrets.CERTIFICATE_BASE64 }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
          KEYCHAIN_PASSWORD:    ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create a temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

          # Import certificate (use empty string if no password was set)
          echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "${CERTIFICATE_PASSWORD:-}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          # Clean up certificate file
          rm certificate.p12

      - name: Setup environment
        run: |
          arch=$(uname -m)
          os=$(echo "$(uname)$(uname -r)" | tr '[:upper:]' '[:lower:]')
          cat <<EOF > $GITHUB_ENV
          suffix=${arch}-apple-${os}
          EOF

      - name: Minimal kit (No GUI)
        run: |
          export KITCREATOR_PKGS="$(awk '{printf "%s ", $0}' .github/workflows/pkgs-nogui-minimal.txt)"
          ./build/pre.sh
          ./kitcreator build ${{env.TCL_TK_VERSION}} --enable-tcl-private-headers
          mv tclkit-${{env.TCL_TK_VERSION}} tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          echo "$KITCREATOR_PKGS" > tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal.kc_packages
          cat <<EOF > $GITHUB_ENV
          TCLKIT=$(pwd)/tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          TCLSH_NATIVE=$(pwd)/tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          EOF

      - name: Minimal kit (With GUI)
        run: |
          export KITCREATOR_PKGS="$(awk '{printf "%s ", $0}' .github/workflows/pkgs-gui-minimal.txt)"
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-aqua --enable-tcl-private-headers
          mv tclkit-${{env.TCL_TK_VERSION}} tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
          echo "$KITCREATOR_PKGS" > tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal.kc_packages
          rm -f  tk/.success
          rm -rf tk/{out,inst,build}

      - name: Standard kit (No GUI)
        run: |
          export KITCREATOR_PKGS="$(awk '{printf "%s ", $0}' .github/workflows/pkgs-nogui-full.txt)"
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-tcl-private-headers
          mv tclkit-${{env.TCL_TK_VERSION}} tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}
          echo "$KITCREATOR_PKGS" > tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}.kc_packages

      - name: Full kit (with GUI)
        run: |
          export KITCREATOR_PKGS="$(awk '{printf "%s ", $0}' .github/workflows/pkgs-gui-full.txt)"
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-aqua --enable-tcl-private-headers
          mv tclkit-${{env.TCL_TK_VERSION}} tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}
          echo "$KITCREATOR_PKGS" > tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}.kc_packages

      - name: Kit SDK
        env:
          STATICTK: 1
        run: |
          export KITCREATOR_PKGS="$(awk '{printf "%s ", $0}' .github/workflows/pkgs-kitdll.txt)"
          clean_all_but_tcl_and_mk4() {
            for pkg in $(ls */build.sh | cut -d/ -f1 | egrep -v '^(tcl|tls|tdom|parse_args|mk4tcl|tcllib)$'); do
              rm -f  "${pkg}/.success"
              rm -rf "${pkg}/out" "${pkg}/inst" "${pkg}/build"
            done
          }
          clean_all_but_tcl_and_mk4
          ./kitcreator retry ${{env.TCL_TK_VERSION}} --enable-aqua --enable-tcl-private-headers --enable-kit-storage=mk4
          mv libtclkit-sdk-${{env.TCL_TK_VERSION}}.tar.gz libtclkit-sdk-${{env.TCL_TK_VERSION}}-${{env.suffix}}.tar.gz
          echo "$KITCREATOR_PKGS" > libtclkit-sdk-${{env.TCL_TK_VERSION}}-${{env.suffix}}.tar.gz.kc_packages

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: kitcreator-macos-logs
          path: |
            **/build.log
            **/config.log
        if: ${{ !cancelled() }}

      - name: Upload kitcreator output
        uses: actions/upload-artifact@v4
        with:
          name: kitcreator-macos-kits
          path: |
            tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
            tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}-minimal
            tclkitsh-${{env.TCL_TK_VERSION}}-${{env.suffix}}
            tclkit-${{env.TCL_TK_VERSION}}-${{env.suffix}}
            libtclkit-sdk-${{env.TCL_TK_VERSION}}-${{env.suffix}}.tar.gz
        if: ${{ !cancelled() }}

      - name: Upload kitcreator package list
        uses: actions/upload-artifact@v4
        with:
          name: kitcreator-macos-kc_packages
          path: |
            *.kc_packages
        if: ${{ !cancelled() }}
